# Generated by Django 6.0.1 on 2026-01-29 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_templateversion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templateversion',
            old_name='version_number',
            new_name='version',
        ),
        migrations.RemoveField(
            model_name='template',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='template',
            name='version',
        ),
        migrations.RemoveField(
            model_name='templateversion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='templateversion',
            name='data',
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='templateversion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.template'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.templateversion')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.section')),
            ],
        ),
    ]
